[package]
name = "fmyers"
version = "0.1.0"
authors = ["baekhyun <543683487@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"

[[bin]]
name = "example"
path = "examples/example.rs"
